server:
  port: 8083

spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:mysql://localhost:3306/tour_booking_db
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

services:
  tour-base-url: http://localhost:8082
  notification-base-url: http://localhost:8084
